name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        ruby: [2.6, 2.7, '3.0', 3.1, 3.2]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: before_setup on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update && sudo apt-get install -yq libboost-all-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: preparation on Windows
      if: runner.os == 'Windows'
      run: |
        pacman -Syy
        pacman -Ssq '\-boost$' | pacman -S --noconfirm -
    - name: Run the default task
      run: bundle exec rake
